class_name PropCatalogIds
extends RefCounted

## Generated by tools/build_prop_catalog.py from documentation/prop-library.md.
## Edit the Markdown registry, then rebuild; do not hand-edit this file.

const PRP_PARK_001: StringName = &"PRP-PARK-001"
const PRP_PARK_002: StringName = &"PRP-PARK-002"
const PRP_PARK_003: StringName = &"PRP-PARK-003"
const PRP_PARK_004: StringName = &"PRP-PARK-004"
const PRP_PARK_005: StringName = &"PRP-PARK-005"
const PRP_PARK_006: StringName = &"PRP-PARK-006"
const PRP_PARK_007: StringName = &"PRP-PARK-007"
const PRP_PARK_008: StringName = &"PRP-PARK-008"
const PRP_PARK_009: StringName = &"PRP-PARK-009"
const PRP_PARK_010: StringName = &"PRP-PARK-010"
const PRP_PARK_011: StringName = &"PRP-PARK-011"
const PRP_PARK_012: StringName = &"PRP-PARK-012"
const PRP_PARK_013: StringName = &"PRP-PARK-013"
const PRP_PARK_014: StringName = &"PRP-PARK-014"
const PRP_PARK_015: StringName = &"PRP-PARK-015"
const PRP_PARK_016: StringName = &"PRP-PARK-016"
const PRP_PARK_017: StringName = &"PRP-PARK-017"
const PRP_PARK_018: StringName = &"PRP-PARK-018"
const PRP_PARK_019: StringName = &"PRP-PARK-019"
const PRP_PARK_020: StringName = &"PRP-PARK-020"
const PRP_PARK_021: StringName = &"PRP-PARK-021"
const PRP_PARK_022: StringName = &"PRP-PARK-022"
const PRP_PARK_023: StringName = &"PRP-PARK-023"
const PRP_LITE_001: StringName = &"PRP-LITE-001"
const PRP_LITE_002: StringName = &"PRP-LITE-002"
const PRP_LITE_003: StringName = &"PRP-LITE-003"
const PRP_LITE_004: StringName = &"PRP-LITE-004"
const PRP_LITE_005: StringName = &"PRP-LITE-005"
const PRP_COAST_001: StringName = &"PRP-COAST-001"
const PRP_COAST_002: StringName = &"PRP-COAST-002"
const PRP_COAST_003: StringName = &"PRP-COAST-003"
const PRP_COAST_004: StringName = &"PRP-COAST-004"
const PRP_COAST_005: StringName = &"PRP-COAST-005"
const PRP_COAST_006: StringName = &"PRP-COAST-006"
const PRP_COAST_007: StringName = &"PRP-COAST-007"
const PRP_COAST_008: StringName = &"PRP-COAST-008"
const PRP_COAST_009: StringName = &"PRP-COAST-009"
const PRP_COAST_010: StringName = &"PRP-COAST-010"
const PRP_COAST_011: StringName = &"PRP-COAST-011"
const PRP_WILD_001: StringName = &"PRP-WILD-001"
const PRP_WILD_002: StringName = &"PRP-WILD-002"
const PRP_WILD_003: StringName = &"PRP-WILD-003"
const PRP_GAME_001: StringName = &"PRP-GAME-001"
const PRP_GAME_002: StringName = &"PRP-GAME-002"
const PRP_GAME_003: StringName = &"PRP-GAME-003"
const PRP_GAME_004: StringName = &"PRP-GAME-004"
const PRP_GAME_005: StringName = &"PRP-GAME-005"
const PRP_GAME_006: StringName = &"PRP-GAME-006"
const PRP_FOOD_001: StringName = &"PRP-FOOD-001"
const PRP_FOOD_002: StringName = &"PRP-FOOD-002"
const PRP_FOOD_003: StringName = &"PRP-FOOD-003"
const PRP_FOOD_004: StringName = &"PRP-FOOD-004"
const PRP_FOOD_005: StringName = &"PRP-FOOD-005"
const PRP_FOOD_006: StringName = &"PRP-FOOD-006"
const PRP_FOOD_007: StringName = &"PRP-FOOD-007"
const PRP_FOOD_008: StringName = &"PRP-FOOD-008"
const PRP_PHOTO_001: StringName = &"PRP-PHOTO-001"
const PRP_PHOTO_002: StringName = &"PRP-PHOTO-002"
const PRP_PHOTO_003: StringName = &"PRP-PHOTO-003"
const PRP_PHOTO_004: StringName = &"PRP-PHOTO-004"
const PRP_PHOTO_005: StringName = &"PRP-PHOTO-005"
const PRP_PHOTO_006: StringName = &"PRP-PHOTO-006"
const PRP_OPS_001: StringName = &"PRP-OPS-001"
const PRP_OPS_002: StringName = &"PRP-OPS-002"
const PRP_OPS_003: StringName = &"PRP-OPS-003"
const PRP_OPS_004: StringName = &"PRP-OPS-004"
const PRP_OPS_005: StringName = &"PRP-OPS-005"
const PRP_OPS_006: StringName = &"PRP-OPS-006"
const PRP_OPS_007: StringName = &"PRP-OPS-007"
const PRP_OPS_008: StringName = &"PRP-OPS-008"
const PRP_OPS_009: StringName = &"PRP-OPS-009"
const PRP_OPS_010: StringName = &"PRP-OPS-010"
const PRP_OPS_011: StringName = &"PRP-OPS-011"
const PRP_OPS_012: StringName = &"PRP-OPS-012"
const PRP_OPS_013: StringName = &"PRP-OPS-013"
const PRP_OPS_014: StringName = &"PRP-OPS-014"
const PRP_OPS_015: StringName = &"PRP-OPS-015"
const PRP_OPS_016: StringName = &"PRP-OPS-016"
const PRP_PLANT_001: StringName = &"PRP-PLANT-001"
const PRP_PLANT_002: StringName = &"PRP-PLANT-002"
const PRP_PLANT_003: StringName = &"PRP-PLANT-003"
const PRP_PLANT_004: StringName = &"PRP-PLANT-004"
const PRP_PLANT_005: StringName = &"PRP-PLANT-005"
const PRP_PLANT_006: StringName = &"PRP-PLANT-006"
const PRP_PLANT_007: StringName = &"PRP-PLANT-007"
const PRP_PLANT_008: StringName = &"PRP-PLANT-008"
const PRP_PLANT_009: StringName = &"PRP-PLANT-009"
const PRP_PLANT_010: StringName = &"PRP-PLANT-010"
const PRP_PLANT_011: StringName = &"PRP-PLANT-011"
const PRP_PLANT_012: StringName = &"PRP-PLANT-012"
const PRP_PLANT_013: StringName = &"PRP-PLANT-013"
const PRP_PLANT_014: StringName = &"PRP-PLANT-014"
const PRP_PLANT_015: StringName = &"PRP-PLANT-015"
const PRP_PLANT_016: StringName = &"PRP-PLANT-016"
const PRP_PLANT_017: StringName = &"PRP-PLANT-017"
const PRP_PLANT_018: StringName = &"PRP-PLANT-018"
const PRP_PLANT_019: StringName = &"PRP-PLANT-019"
const PRP_PLANT_020: StringName = &"PRP-PLANT-020"
const PRP_PLANT_021: StringName = &"PRP-PLANT-021"
const PRP_PLANT_022: StringName = &"PRP-PLANT-022"
const PRP_PLANT_023: StringName = &"PRP-PLANT-023"
const PRP_PLANT_024: StringName = &"PRP-PLANT-024"
const PRP_PLANT_025: StringName = &"PRP-PLANT-025"
const PRP_PLANT_026: StringName = &"PRP-PLANT-026"
const PRP_PLANT_027: StringName = &"PRP-PLANT-027"
const PRP_PLANT_028: StringName = &"PRP-PLANT-028"
const PRP_PLANT_029: StringName = &"PRP-PLANT-029"
const PRP_PLANT_030: StringName = &"PRP-PLANT-030"
const PRP_PLANT_031: StringName = &"PRP-PLANT-031"
const PRP_PLANT_032: StringName = &"PRP-PLANT-032"
const PRP_PLANT_033: StringName = &"PRP-PLANT-033"
const PRP_PLANT_034: StringName = &"PRP-PLANT-034"
const PRP_PLANT_035: StringName = &"PRP-PLANT-035"
const PRP_PLANT_036: StringName = &"PRP-PLANT-036"
const PRP_PLANT_037: StringName = &"PRP-PLANT-037"
const PRP_PLANT_038: StringName = &"PRP-PLANT-038"
const PRP_PLANT_039: StringName = &"PRP-PLANT-039"
const PRP_PLANT_040: StringName = &"PRP-PLANT-040"
const PRP_PLANT_041: StringName = &"PRP-PLANT-041"
const PRP_PLANT_042: StringName = &"PRP-PLANT-042"
const PRP_PLANT_043: StringName = &"PRP-PLANT-043"
const PRP_PLANT_044: StringName = &"PRP-PLANT-044"
const PRP_PLANT_045: StringName = &"PRP-PLANT-045"
const PRP_PLANT_046: StringName = &"PRP-PLANT-046"
const PRP_PLANT_047: StringName = &"PRP-PLANT-047"
const PRP_PLANT_048: StringName = &"PRP-PLANT-048"
const PRP_PLANT_049: StringName = &"PRP-PLANT-049"
const PRP_PLANT_050: StringName = &"PRP-PLANT-050"
const PRP_PLANT_051: StringName = &"PRP-PLANT-051"
const PRP_FENCE_001: StringName = &"PRP-FENCE-001"
const PRP_FENCE_002: StringName = &"PRP-FENCE-002"
const PRP_TRANSIT_001: StringName = &"PRP-TRANSIT-001"
const PRP_TRANSIT_002: StringName = &"PRP-TRANSIT-002"
const PRP_ROAD_001: StringName = &"PRP-ROAD-001"
const PRP_ROAD_002: StringName = &"PRP-ROAD-002"
const PRP_ROAD_003: StringName = &"PRP-ROAD-003"
const PRP_ROAD_004: StringName = &"PRP-ROAD-004"
const PRP_TOWN_001: StringName = &"PRP-TOWN-001"
const PRP_TOWN_002: StringName = &"PRP-TOWN-002"
const PRP_TOWN_003: StringName = &"PRP-TOWN-003"
const PRP_STORY_001: StringName = &"PRP-STORY-001"
const PRP_STORY_002: StringName = &"PRP-STORY-002"
const PRP_STORY_003: StringName = &"PRP-STORY-003"
const PRP_STORY_004: StringName = &"PRP-STORY-004"
const PRP_STORY_005: StringName = &"PRP-STORY-005"
const PRP_STORY_006: StringName = &"PRP-STORY-006"
const PRP_STORY_007: StringName = &"PRP-STORY-007"
const PRP_STORY_008: StringName = &"PRP-STORY-008"
const PRP_STORY_009: StringName = &"PRP-STORY-009"
const PRP_STORY_010: StringName = &"PRP-STORY-010"
const PRP_STORY_011: StringName = &"PRP-STORY-011"
const PRP_STORY_012: StringName = &"PRP-STORY-012"
const PRP_STORY_013: StringName = &"PRP-STORY-013"
const PRP_STORY_014: StringName = &"PRP-STORY-014"
const PRP_STORY_015: StringName = &"PRP-STORY-015"
const PRP_PHOTO_007: StringName = &"PRP-PHOTO-007"
const PRP_PHOTO_008: StringName = &"PRP-PHOTO-008"
const PRP_PHOTO_009: StringName = &"PRP-PHOTO-009"
const PRP_PHOTO_010: StringName = &"PRP-PHOTO-010"
const PRP_PHOTO_011: StringName = &"PRP-PHOTO-011"
const PRP_PHOTO_012: StringName = &"PRP-PHOTO-012"
const PRP_PHOTO_013: StringName = &"PRP-PHOTO-013"
const PRP_PHOTO_014: StringName = &"PRP-PHOTO-014"
const PRP_OPS_017: StringName = &"PRP-OPS-017"
const PRP_OPS_018: StringName = &"PRP-OPS-018"
const PRP_OPS_019: StringName = &"PRP-OPS-019"
const PRP_OPS_020: StringName = &"PRP-OPS-020"
const PRP_OPS_021: StringName = &"PRP-OPS-021"
const PRP_OPS_022: StringName = &"PRP-OPS-022"
const PRP_OPS_023: StringName = &"PRP-OPS-023"
const PRP_SEASON_001: StringName = &"PRP-SEASON-001"
const PRP_SEASON_002: StringName = &"PRP-SEASON-002"
const PRP_SEASON_003: StringName = &"PRP-SEASON-003"
const PRP_SEASON_004: StringName = &"PRP-SEASON-004"
const PRP_SEASON_005: StringName = &"PRP-SEASON-005"
const PRP_SEASON_006: StringName = &"PRP-SEASON-006"
const PRP_SEASON_007: StringName = &"PRP-SEASON-007"
const PRP_SEASON_008: StringName = &"PRP-SEASON-008"
const PRP_SEASON_009: StringName = &"PRP-SEASON-009"
const PRP_SEASON_010: StringName = &"PRP-SEASON-010"
const PRP_SEASON_011: StringName = &"PRP-SEASON-011"
const PRP_SEASON_012: StringName = &"PRP-SEASON-012"
const PRP_SEASON_013: StringName = &"PRP-SEASON-013"
const PRP_SEASON_014: StringName = &"PRP-SEASON-014"
const PRP_SEASON_015: StringName = &"PRP-SEASON-015"
const PRP_SEASON_016: StringName = &"PRP-SEASON-016"
const PRP_SEASON_017: StringName = &"PRP-SEASON-017"
const PRP_SEASON_018: StringName = &"PRP-SEASON-018"
const GRP_PLAZA_001: StringName = &"GRP-PLAZA-001"
const GRP_PLAZA_002: StringName = &"GRP-PLAZA-002"
const GRP_PLAZA_003: StringName = &"GRP-PLAZA-003"
const GRP_PLAZA_004: StringName = &"GRP-PLAZA-004"
const GRP_PARK_001: StringName = &"GRP-PARK-001"
const GRP_PARK_002: StringName = &"GRP-PARK-002"
const GRP_PARK_003: StringName = &"GRP-PARK-003"
const GRP_PARK_004: StringName = &"GRP-PARK-004"
const GRP_PARK_005: StringName = &"GRP-PARK-005"
const GRP_PARK_006: StringName = &"GRP-PARK-006"
const GRP_PARK_007: StringName = &"GRP-PARK-007"
const GRP_PARK_008: StringName = &"GRP-PARK-008"
const GRP_PARK_009: StringName = &"GRP-PARK-009"
const GRP_PARK_010: StringName = &"GRP-PARK-010"
const GRP_PARK_011: StringName = &"GRP-PARK-011"
const GRP_PARK_012: StringName = &"GRP-PARK-012"
const GRP_PARK_013: StringName = &"GRP-PARK-013"
const GRP_PARK_014: StringName = &"GRP-PARK-014"
const GRP_PARK_015: StringName = &"GRP-PARK-015"
const GRP_PARK_016: StringName = &"GRP-PARK-016"
const GRP_PARK_017: StringName = &"GRP-PARK-017"
const GRP_PARK_018: StringName = &"GRP-PARK-018"
const GRP_BW_001: StringName = &"GRP-BW-001"
const GRP_BW_002: StringName = &"GRP-BW-002"
const GRP_BW_003: StringName = &"GRP-BW-003"
const GRP_BW_004: StringName = &"GRP-BW-004"
const GRP_BW_005: StringName = &"GRP-BW-005"
const GRP_BW_006: StringName = &"GRP-BW-006"
const GRP_BW_007: StringName = &"GRP-BW-007"
const GRP_BW_008: StringName = &"GRP-BW-008"
const GRP_BW_009: StringName = &"GRP-BW-009"
const GRP_BW_010: StringName = &"GRP-BW-010"
const GRP_BW_011: StringName = &"GRP-BW-011"
const GRP_BW_012: StringName = &"GRP-BW-012"
const GRP_BW_013: StringName = &"GRP-BW-013"
const GRP_BW_014: StringName = &"GRP-BW-014"
const GRP_BW_015: StringName = &"GRP-BW-015"
const GRP_BW_016: StringName = &"GRP-BW-016"
const GRP_BW_017: StringName = &"GRP-BW-017"
const GRP_BW_018: StringName = &"GRP-BW-018"
const GRP_BW_019: StringName = &"GRP-BW-019"
const GRP_BW_020: StringName = &"GRP-BW-020"
const GRP_BW_021: StringName = &"GRP-BW-021"
const GRP_BW_022: StringName = &"GRP-BW-022"
const GRP_BW_023: StringName = &"GRP-BW-023"
const GRP_BW_024: StringName = &"GRP-BW-024"
const GRP_BW_025: StringName = &"GRP-BW-025"
const GRP_BW_026: StringName = &"GRP-BW-026"
const GRP_BW_027: StringName = &"GRP-BW-027"
const GRP_BW_028: StringName = &"GRP-BW-028"
const GRP_PHOTO_001: StringName = &"GRP-PHOTO-001"
const GRP_PHOTO_002: StringName = &"GRP-PHOTO-002"
const GRP_PHOTO_003: StringName = &"GRP-PHOTO-003"
const GRP_STORY_001: StringName = &"GRP-STORY-001"
const GRP_STORY_002: StringName = &"GRP-STORY-002"
const GRP_STORY_003: StringName = &"GRP-STORY-003"
const GRP_STORY_004: StringName = &"GRP-STORY-004"
const GRP_SEASON_001: StringName = &"GRP-SEASON-001"
const GRP_SEASON_002: StringName = &"GRP-SEASON-002"
const GRP_SEASON_003: StringName = &"GRP-SEASON-003"
const GRP_SEASON_004: StringName = &"GRP-SEASON-004"
const GRP_SEASON_005: StringName = &"GRP-SEASON-005"

const DISPLAY_NAMES: Dictionary = {
	PRP_PARK_001: "Cast-frame slatted park bench",
	PRP_PARK_002: "Waste bin",
	PRP_PARK_003: "Picture-spot sign",
	PRP_PARK_004: "A-frame notice sign",
	PRP_PARK_005: "Newspaper box",
	PRP_PARK_006: "Flagpole and vertical banner",
	PRP_PARK_007: "General service cart",
	PRP_PARK_008: "Guest stroller",
	PRP_PARK_009: "Maintenance ladder",
	PRP_PARK_010: "Tied balloon cluster",
	PRP_PARK_011: "Park litter",
	PRP_PARK_012: "Picnic table",
	PRP_PARK_013: "Café table set",
	PRP_PARK_014: "Rope queue stanchion",
	PRP_PARK_015: "Protective bollard",
	PRP_PARK_016: "Framed poster or display case",
	PRP_PARK_017: "Public payphone",
	PRP_PARK_018: "Perforated metal bench",
	PRP_PARK_019: "Backless timber bench",
	PRP_PARK_020: "Drive-in picnic table set",
	PRP_PARK_021: "Circular drive-in picnic table set",
	PRP_PARK_022: "Granite-block circular picnic table",
	PRP_PARK_023: "Color-block information panel",
	PRP_LITE_001: "Park lamp standard",
	PRP_LITE_002: "Wall practical",
	PRP_LITE_003: "Festoon kit",
	PRP_LITE_004: "Ride-outline incandescent",
	PRP_LITE_005: "Tree light string",
	PRP_COAST_001: "Boardwalk coastal-color planter",
	PRP_COAST_002: "Pier cleat",
	PRP_COAST_003: "Life ring and bracket",
	PRP_COAST_004: "Wheel gondola, red",
	PRP_COAST_005: "Wheel gondola, yellow",
	PRP_COAST_006: "Coastal palm crown",
	PRP_COAST_007: "Coastal palm trunk",
	PRP_COAST_008: "Boardwalk promenade cart",
	PRP_COAST_009: "Back-lane stock cart",
	PRP_COAST_010: "Creek-bank stone",
	PRP_COAST_011: "Reclined waterfront viewing bench",
	PRP_WILD_001: "Adult coastal gull",
	PRP_WILD_002: "Mottled juvenile gull",
	PRP_WILD_003: "Rock dove",
	PRP_GAME_001: "Arcade cabinet",
	PRP_GAME_002: "Derby-race lane and horse target",
	PRP_GAME_003: "Derby prize display",
	PRP_GAME_004: "Coin-pitch table and plates",
	PRP_GAME_005: "Basket-toss basket, ball and rack",
	PRP_GAME_006: "Midway prize rail and shelf",
	PRP_FOOD_001: "Service-window menu board",
	PRP_FOOD_002: "Pie display case",
	PRP_FOOD_003: "Concession counter equipment",
	PRP_FOOD_004: "Service freezer box",
	PRP_FOOD_005: "Delivery crate",
	PRP_FOOD_006: "Condiment and napkin set",
	PRP_FOOD_007: "Used tray and funnel-cake remnant",
	PRP_FOOD_008: "Park refill cup",
	PRP_PHOTO_001: "Ride-photo counter",
	PRP_PHOTO_002: "Ride-photo CRT and monitor bank",
	PRP_PHOTO_003: "Claim-slip stack",
	PRP_PHOTO_004: "Operator stool",
	PRP_PHOTO_005: "Mounted sample ride photo",
	PRP_PHOTO_006: "Print packet stack",
	PRP_OPS_001: "Boarding/load/exit gate",
	PRP_OPS_002: "Wheel operator control",
	PRP_OPS_003: "Wheel step-free boarding lift",
	PRP_OPS_004: "Maintenance locker and storage",
	PRP_OPS_005: "Coaster brake console",
	PRP_OPS_006: "Block lamp and emergency stop",
	PRP_OPS_007: "Maintenance hose and reel",
	PRP_OPS_008: "Specialist work cart",
	PRP_OPS_009: "Funhouse entry turnstile",
	PRP_OPS_010: "Funhouse operator box and show stop",
	PRP_OPS_011: "Service door and operating notice",
	PRP_OPS_012: "Fish-cleaning sink and cutting board",
	PRP_OPS_013: "Tackle cart",
	PRP_OPS_014: "Rod rack and fishing rods",
	PRP_OPS_015: "Cleanup bin and drain bucket",
	PRP_OPS_016: "Folded stock cart and empty crate",
	PRP_PLANT_001: "Shade tree",
	PRP_PLANT_002: "Raised planter with clipped shrub",
	PRP_PLANT_003: "Trellis and vine panel",
	PRP_PLANT_004: "Creek sedge and reed clump",
	PRP_PLANT_005: "Pond lily cluster",
	PRP_PLANT_006: "Banana accent tree vA",
	PRP_PLANT_007: "Banana accent tree vB",
	PRP_PLANT_008: "Banana accent tree vC",
	PRP_PLANT_009: "Landscaped palm soil bed",
	PRP_PLANT_010: "Boardwalk palm tree box",
	PRP_PLANT_011: "Coastal fern fan",
	PRP_PLANT_012: "Red Sensation cabbage tree vA",
	PRP_PLANT_013: "Red Sensation cabbage tree vB",
	PRP_PLANT_014: "Red Sensation cabbage tree vC",
	PRP_PLANT_015: "Purple Heart planting row vA",
	PRP_PLANT_016: "Purple Heart planting row vB",
	PRP_PLANT_017: "Purple Heart trailing cluster",
	PRP_PLANT_018: "Lemon Zest Hakone grass clump vA",
	PRP_PLANT_019: "Lemon Zest Hakone grass clump vB",
	PRP_PLANT_020: "Lemon Zest Hakone grass row",
	PRP_PLANT_021: "Lemon Zest Hakone grass ring",
	PRP_PLANT_022: "Blue delphinium clump",
	PRP_PLANT_023: "Purple delphinium clump",
	PRP_PLANT_024: "White delphinium clump",
	PRP_PLANT_025: "Mixed delphinium border",
	PRP_PLANT_026: "Mixed-flower coir hanging basket",
	PRP_PLANT_027: "Fern hanging bowl",
	PRP_PLANT_028: "Purple Heart cedar hanging box",
	PRP_PLANT_029: "Deep-green Lily of the Nile clump",
	PRP_PLANT_030: "Former range conifer placeholder",
	PRP_PLANT_031: "Former range broadleaf placeholder",
	PRP_PLANT_032: "Mature Grove shade tree",
	PRP_PLANT_033: "Overflowing mixed-petunia hanging basket",
	PRP_PLANT_034: "Multi-stem white-bark shade tree",
	PRP_PLANT_035: "Low clipped hedge module",
	PRP_PLANT_036: "Dark lilyturf clump",
	PRP_PLANT_037: "Dark lilyturf row",
	PRP_PLANT_038: "Coastal redwood, old-growth high crown",
	PRP_PLANT_039: "Coastal redwood, younger spire",
	PRP_PLANT_040: "Coastal redwood, wind-shaped high crown",
	PRP_PLANT_041: "Coastal Douglas fir",
	PRP_PLANT_042: "Light yellow-green Lily of the Nile clump",
	PRP_PLANT_043: "Light yellow-green lilyturf clump",
	PRP_PLANT_044: "Light yellow-green lilyturf row",
	PRP_PLANT_045: "Compact fan palmetto",
	PRP_PLANT_046: "Classic bay laurel",
	PRP_PLANT_047: "Torbay Dazzler cordyline",
	PRP_PLANT_048: "Electric Pink cordyline",
	PRP_PLANT_049: "California coast live oak",
	PRP_PLANT_050: "Mature classic bay laurel",
	PRP_PLANT_051: "Classic California date palm",
	PRP_FENCE_001: "Black ornamental garden fence",
	PRP_FENCE_002: "Plain waterfront guardrail",
	PRP_TRANSIT_001: "Station barrier and platform guard",
	PRP_TRANSIT_002: "Road/rail crossing marker",
	PRP_ROAD_001: "Cobra-head road lamp",
	PRP_ROAD_002: "Traffic-signal mast and head",
	PRP_ROAD_003: "Stop sign",
	PRP_ROAD_004: "Road barrier and guardrail",
	PRP_TOWN_001: "Historic twin lantern and hanging basket",
	PRP_TOWN_002: "Residential post lamp",
	PRP_TOWN_003: "Beach-town mariner lamp",
	PRP_STORY_001: "Pulp-horror paperback",
	PRP_STORY_002: "Story key on a shoelace",
	PRP_STORY_003: "Lawn gnome",
	PRP_STORY_004: "Giant prize gnome",
	PRP_STORY_005: "Disposable camera",
	PRP_STORY_006: "Old-logo refill cup",
	PRP_STORY_007: "Pressed penny",
	PRP_STORY_008: "Birthday board",
	PRP_STORY_009: "Story box",
	PRP_STORY_010: "Photo Hut key peg-board",
	PRP_STORY_011: "Park map or postcard by year",
	PRP_STORY_012: "Tagged lost-and-found object",
	PRP_STORY_013: "Frontier production prop",
	PRP_STORY_014: "Half-eaten meal",
	PRP_STORY_015: "Dropped balloon at a rail",
	PRP_PHOTO_007: "Film drop box",
	PRP_PHOTO_008: "Film roll box or cartridge",
	PRP_PHOTO_009: "Assignment sheet and shot-list card",
	PRP_PHOTO_010: "Claim ticket and customer stub",
	PRP_PHOTO_011: "Print envelope and mounted print",
	PRP_PHOTO_012: "Contact sheet and unclaimed print",
	PRP_PHOTO_013: "Minilab and wet-side tools",
	PRP_PHOTO_014: "Light table",
	PRP_OPS_017: "Staff radio",
	PRP_OPS_018: "Paper calendar and duty board",
	PRP_OPS_019: "Punch clock and time cards",
	PRP_OPS_020: "Incident log",
	PRP_OPS_021: "Staff locker",
	PRP_OPS_022: "Break-room vending machine",
	PRP_OPS_023: "Break-room plastic table and chair",
	PRP_SEASON_001: "Cloth bunting",
	PRP_SEASON_002: "Paper pennant and maritime signal flag",
	PRP_SEASON_003: "C7/C9 incandescent string",
	PRP_SEASON_004: "Paper lantern",
	PRP_SEASON_005: "Seasonal pole banner",
	PRP_SEASON_006: "Painted-plywood event sign",
	PRP_SEASON_007: "Window card and menu swap",
	PRP_SEASON_008: "Removable photo backdrop",
	PRP_SEASON_009: "Seasonal planter and ribboned sapling",
	PRP_SEASON_010: "Pumpkin, corn bundle and hay bale",
	PRP_SEASON_011: "Evergreen rope",
	PRP_SEASON_012: "Foil star and snowflake",
	PRP_SEASON_013: "Rain mat and portable heater",
	PRP_SEASON_014: "Character costume accessory and rain gear",
	PRP_SEASON_015: "Ride tarp and half-shutter",
	PRP_SEASON_016: "Closure board and inspection tag",
	PRP_SEASON_017: "Queue placard",
	PRP_SEASON_018: "Seasonal stock cart",
	GRP_PLAZA_001: "Plaza public-furniture field",
	GRP_PLAZA_002: "Plaza café terrace",
	GRP_PLAZA_003: "Photo Hut exterior queue",
	GRP_PLAZA_004: "Plaza service residue",
	GRP_PARK_001: "Eastern promenade furnishing",
	GRP_PARK_002: "Frontier working-street dressing",
	GRP_PARK_003: "Kiddieland Family Commons",
	GRP_PARK_004: "Fairground public and midway dressing",
	GRP_PARK_005: "Grove picnic and garden dressing",
	GRP_PARK_006: "Grand Circuit stop and crossing furniture",
	GRP_PARK_007: "Coastal palm placement set",
	GRP_PARK_008: "Park approach/highway furniture",
	GRP_PARK_009: "Town street-light families",
	GRP_PARK_010: "Layered arrival palm bed",
	GRP_PARK_011: "Dense parkway show bed",
	GRP_PARK_012: "Coastal palm whole-tree specimen",
	GRP_PARK_013: "Single-bracket petunia basket",
	GRP_PARK_014: "Twin-basket heritage lamp",
	GRP_PARK_015: "Petunia lamp mini row",
	GRP_PARK_016: "Furniture-free petunia ground row",
	GRP_PARK_017: "Shaded waterfront promenade vignette",
	GRP_PARK_018: "Classic bay laurel stand",
	GRP_BW_001: "I2 arcade and ride-photo counter",
	GRP_BW_002: "I3 Boardwalk café",
	GRP_BW_003: "B1 derby race",
	GRP_BW_004: "B2 coin pitch",
	GRP_BW_005: "B3 basket toss",
	GRP_BW_006: "B4 taffy and funnel cake",
	GRP_BW_007: "Shared service residue",
	GRP_BW_008: "R1 wheel operations",
	GRP_BW_009: "R2 coaster station operations",
	GRP_BW_010: "P2 funhouse operations",
	GRP_BW_011: "Pier fishing operations",
	GRP_BW_012: "S1/S2 service connections",
	GRP_BW_013: "Coastal-planter rhythm",
	GRP_BW_014: "Promenade-bin rhythm",
	GRP_BW_015: "Period frontage furniture",
	GRP_BW_016: "Pier-edge hardware",
	GRP_BW_017: "I2 ride-photo merchandise",
	GRP_BW_018: "Midway merchandise",
	GRP_BW_019: "Café working residue",
	GRP_BW_020: "Selective practical fixtures",
	GRP_BW_021: "Creek bank stones",
	GRP_BW_022: "Creek planting",
	GRP_BW_023: "Bridge-edge detail",
	GRP_BW_024: "Wheel gondola set",
	GRP_BW_025: "Wheel incandescent outline",
	GRP_BW_026: "Coaster station train and operating furniture",
	GRP_BW_027: "Pier-head safety and circulation furniture",
	GRP_BW_028: "Pier House practical fixtures",
	GRP_PHOTO_001: "Photo Hut working counter",
	GRP_PHOTO_002: "Photo Hut minilab and archive",
	GRP_PHOTO_003: "Photo Hut staff record wall",
	GRP_STORY_001: "Shared period story-object kit",
	GRP_STORY_002: "Recently vacated night residue",
	GRP_STORY_003: "Grove gnome set",
	GRP_STORY_004: "Kiddieland story-box and key circuit",
	GRP_SEASON_001: "Overhead seasonal kit",
	GRP_SEASON_002: "Vertical seasonal kit",
	GRP_SEASON_003: "Edge seasonal kit",
	GRP_SEASON_004: "Weather and character kit",
	GRP_SEASON_005: "Operating-state kit",
}

const STATUSES: Dictionary = {
	PRP_PARK_001: &"in_review",
	PRP_PARK_002: &"built",
	PRP_PARK_003: &"built",
	PRP_PARK_004: &"built",
	PRP_PARK_005: &"built",
	PRP_PARK_006: &"built",
	PRP_PARK_007: &"built",
	PRP_PARK_008: &"retired",
	PRP_PARK_009: &"retired",
	PRP_PARK_010: &"built",
	PRP_PARK_011: &"built",
	PRP_PARK_012: &"built",
	PRP_PARK_013: &"built",
	PRP_PARK_014: &"built",
	PRP_PARK_015: &"built",
	PRP_PARK_016: &"built",
	PRP_PARK_017: &"built",
	PRP_PARK_018: &"in_review",
	PRP_PARK_019: &"in_review",
	PRP_PARK_020: &"in_review",
	PRP_PARK_021: &"in_review",
	PRP_PARK_022: &"in_review",
	PRP_PARK_023: &"in_review",
	PRP_LITE_001: &"built",
	PRP_LITE_002: &"built",
	PRP_LITE_003: &"built",
	PRP_LITE_004: &"built",
	PRP_LITE_005: &"built",
	PRP_COAST_001: &"built",
	PRP_COAST_002: &"built",
	PRP_COAST_003: &"built",
	PRP_COAST_004: &"built",
	PRP_COAST_005: &"built",
	PRP_COAST_006: &"in_review",
	PRP_COAST_007: &"in_review",
	PRP_COAST_008: &"built",
	PRP_COAST_009: &"built",
	PRP_COAST_010: &"built",
	PRP_COAST_011: &"in_review",
	PRP_WILD_001: &"built",
	PRP_WILD_002: &"built",
	PRP_WILD_003: &"built",
	PRP_GAME_001: &"built",
	PRP_GAME_002: &"built",
	PRP_GAME_003: &"built",
	PRP_GAME_004: &"built",
	PRP_GAME_005: &"built",
	PRP_GAME_006: &"built",
	PRP_FOOD_001: &"built",
	PRP_FOOD_002: &"built",
	PRP_FOOD_003: &"built",
	PRP_FOOD_004: &"built",
	PRP_FOOD_005: &"built",
	PRP_FOOD_006: &"built",
	PRP_FOOD_007: &"built",
	PRP_FOOD_008: &"built",
	PRP_PHOTO_001: &"built",
	PRP_PHOTO_002: &"built",
	PRP_PHOTO_003: &"built",
	PRP_PHOTO_004: &"built",
	PRP_PHOTO_005: &"built",
	PRP_PHOTO_006: &"built",
	PRP_OPS_001: &"built",
	PRP_OPS_002: &"built",
	PRP_OPS_003: &"built",
	PRP_OPS_004: &"built",
	PRP_OPS_005: &"built",
	PRP_OPS_006: &"built",
	PRP_OPS_007: &"built",
	PRP_OPS_008: &"built",
	PRP_OPS_009: &"built",
	PRP_OPS_010: &"built",
	PRP_OPS_011: &"built",
	PRP_OPS_012: &"built",
	PRP_OPS_013: &"built",
	PRP_OPS_014: &"built",
	PRP_OPS_015: &"built",
	PRP_OPS_016: &"built",
	PRP_PLANT_001: &"in_review",
	PRP_PLANT_002: &"built",
	PRP_PLANT_003: &"built",
	PRP_PLANT_004: &"built",
	PRP_PLANT_005: &"built",
	PRP_PLANT_006: &"in_review",
	PRP_PLANT_007: &"in_review",
	PRP_PLANT_008: &"in_review",
	PRP_PLANT_009: &"in_review",
	PRP_PLANT_010: &"in_review",
	PRP_PLANT_011: &"in_review",
	PRP_PLANT_012: &"in_review",
	PRP_PLANT_013: &"in_review",
	PRP_PLANT_014: &"in_review",
	PRP_PLANT_015: &"in_review",
	PRP_PLANT_016: &"in_review",
	PRP_PLANT_017: &"in_review",
	PRP_PLANT_018: &"in_review",
	PRP_PLANT_019: &"in_review",
	PRP_PLANT_020: &"in_review",
	PRP_PLANT_021: &"in_review",
	PRP_PLANT_022: &"in_review",
	PRP_PLANT_023: &"in_review",
	PRP_PLANT_024: &"in_review",
	PRP_PLANT_025: &"in_review",
	PRP_PLANT_026: &"in_review",
	PRP_PLANT_027: &"in_review",
	PRP_PLANT_028: &"in_review",
	PRP_PLANT_029: &"in_review",
	PRP_PLANT_030: &"in_review",
	PRP_PLANT_031: &"in_review",
	PRP_PLANT_032: &"in_review",
	PRP_PLANT_033: &"in_review",
	PRP_PLANT_034: &"in_review",
	PRP_PLANT_035: &"in_review",
	PRP_PLANT_036: &"in_review",
	PRP_PLANT_037: &"in_review",
	PRP_PLANT_038: &"in_review",
	PRP_PLANT_039: &"in_review",
	PRP_PLANT_040: &"in_review",
	PRP_PLANT_041: &"in_review",
	PRP_PLANT_042: &"in_review",
	PRP_PLANT_043: &"in_review",
	PRP_PLANT_044: &"in_review",
	PRP_PLANT_045: &"in_review",
	PRP_PLANT_046: &"in_review",
	PRP_PLANT_047: &"in_review",
	PRP_PLANT_048: &"in_review",
	PRP_PLANT_049: &"in_review",
	PRP_PLANT_050: &"in_review",
	PRP_PLANT_051: &"in_review",
	PRP_FENCE_001: &"in_review",
	PRP_FENCE_002: &"in_review",
	PRP_TRANSIT_001: &"built",
	PRP_TRANSIT_002: &"built",
	PRP_ROAD_001: &"built",
	PRP_ROAD_002: &"built",
	PRP_ROAD_003: &"built",
	PRP_ROAD_004: &"built",
	PRP_TOWN_001: &"built",
	PRP_TOWN_002: &"built",
	PRP_TOWN_003: &"built",
	PRP_STORY_001: &"planned",
	PRP_STORY_002: &"planned",
	PRP_STORY_003: &"planned",
	PRP_STORY_004: &"planned",
	PRP_STORY_005: &"planned",
	PRP_STORY_006: &"planned",
	PRP_STORY_007: &"planned",
	PRP_STORY_008: &"planned",
	PRP_STORY_009: &"planned",
	PRP_STORY_010: &"planned",
	PRP_STORY_011: &"planned",
	PRP_STORY_012: &"planned",
	PRP_STORY_013: &"planned",
	PRP_STORY_014: &"planned",
	PRP_STORY_015: &"planned",
	PRP_PHOTO_007: &"planned",
	PRP_PHOTO_008: &"planned",
	PRP_PHOTO_009: &"planned",
	PRP_PHOTO_010: &"planned",
	PRP_PHOTO_011: &"planned",
	PRP_PHOTO_012: &"planned",
	PRP_PHOTO_013: &"planned",
	PRP_PHOTO_014: &"planned",
	PRP_OPS_017: &"planned",
	PRP_OPS_018: &"planned",
	PRP_OPS_019: &"planned",
	PRP_OPS_020: &"planned",
	PRP_OPS_021: &"planned",
	PRP_OPS_022: &"planned",
	PRP_OPS_023: &"planned",
	PRP_SEASON_001: &"planned",
	PRP_SEASON_002: &"planned",
	PRP_SEASON_003: &"planned",
	PRP_SEASON_004: &"planned",
	PRP_SEASON_005: &"planned",
	PRP_SEASON_006: &"planned",
	PRP_SEASON_007: &"planned",
	PRP_SEASON_008: &"planned",
	PRP_SEASON_009: &"planned",
	PRP_SEASON_010: &"planned",
	PRP_SEASON_011: &"planned",
	PRP_SEASON_012: &"planned",
	PRP_SEASON_013: &"planned",
	PRP_SEASON_014: &"planned",
	PRP_SEASON_015: &"planned",
	PRP_SEASON_016: &"planned",
	PRP_SEASON_017: &"planned",
	PRP_SEASON_018: &"planned",
	GRP_PLAZA_001: &"built",
	GRP_PLAZA_002: &"built",
	GRP_PLAZA_003: &"built",
	GRP_PLAZA_004: &"built",
	GRP_PARK_001: &"built",
	GRP_PARK_002: &"built",
	GRP_PARK_003: &"built",
	GRP_PARK_004: &"built",
	GRP_PARK_005: &"built",
	GRP_PARK_006: &"built",
	GRP_PARK_007: &"in_review",
	GRP_PARK_008: &"built",
	GRP_PARK_009: &"built",
	GRP_PARK_010: &"in_review",
	GRP_PARK_011: &"in_review",
	GRP_PARK_012: &"in_review",
	GRP_PARK_013: &"in_review",
	GRP_PARK_014: &"in_review",
	GRP_PARK_015: &"in_review",
	GRP_PARK_016: &"in_review",
	GRP_PARK_017: &"in_review",
	GRP_PARK_018: &"in_review",
	GRP_BW_001: &"built",
	GRP_BW_002: &"built",
	GRP_BW_003: &"built",
	GRP_BW_004: &"built",
	GRP_BW_005: &"built",
	GRP_BW_006: &"built",
	GRP_BW_007: &"built",
	GRP_BW_008: &"built",
	GRP_BW_009: &"built",
	GRP_BW_010: &"built",
	GRP_BW_011: &"built",
	GRP_BW_012: &"built",
	GRP_BW_013: &"retired",
	GRP_BW_014: &"built",
	GRP_BW_015: &"built",
	GRP_BW_016: &"built",
	GRP_BW_017: &"built",
	GRP_BW_018: &"built",
	GRP_BW_019: &"built",
	GRP_BW_020: &"built",
	GRP_BW_021: &"built",
	GRP_BW_022: &"built",
	GRP_BW_023: &"built",
	GRP_BW_024: &"built",
	GRP_BW_025: &"built",
	GRP_BW_026: &"built",
	GRP_BW_027: &"built",
	GRP_BW_028: &"built",
	GRP_PHOTO_001: &"planned",
	GRP_PHOTO_002: &"planned",
	GRP_PHOTO_003: &"planned",
	GRP_STORY_001: &"planned",
	GRP_STORY_002: &"planned",
	GRP_STORY_003: &"planned",
	GRP_STORY_004: &"planned",
	GRP_SEASON_001: &"planned",
	GRP_SEASON_002: &"planned",
	GRP_SEASON_003: &"planned",
	GRP_SEASON_004: &"planned",
	GRP_SEASON_005: &"planned",
}

static func is_known(label: StringName) -> bool:
	return DISPLAY_NAMES.has(label)

static func display_name(label: StringName) -> String:
	return String(DISPLAY_NAMES.get(label, ""))

static func status(label: StringName) -> StringName:
	return StringName(STATUSES.get(label, &""))
